### ISSUE TITLE
Bug: DEV feedback page

### ISSUE THREAD

**Issue by maulieshah** [hackforla/tdm-calculator#1730] opened 2024-06-06 00:11 UTC
#### Describe the bug 

Users are not able to access feedback page if they do not login the DEV website. Error is showing up as provided in the screenshot below. 

#### Steps to reproduce the issue

(if applicable, please specify platform (iOS, Android, Windows, Mac version) and brower)

REPLACE THE FOLLOWNG TEXT:
- 1. Go to 'Feedback' and DO NOT LOGIN 
- 2. See error 

#### What's the actual result?
Error 

#### Additional details / screenshot

<img width="959" alt="image" src="https://github.com/hackforla/tdm-calculator/assets/167944477/2c39236d-ee31-412a-b326-7dff2c37e913">

#### Device configuration

REPLACE THE FOLLOWNG TEXT:
- Device: [e.g. type of smartphone, tablet, desktop computer]
- OS version: [e.g. iOS, Android version #]
- Browser [e.g. Chrome, Firefox, Safari, etc.]
- Browser version [e.g. 22]

**Comment by entrotech** [comment] 2024-08-05 23:27
- Issue is Duplicate of #1582, fixed on PR #1595

**Closed by entrotech** 2024-08-05 23:27 UTC
Labels: bug, level: easy, priority: MUST HAVE, role: missing, size: 0.5pt, p-feature: Feedback Page
