### ISSUE TITLE
Target Points Calculation Component

### ISSUE THREAD

**Issue by fyliu** [hackforla/tdm-calculator#200] opened 2020-01-15 07:52 UTC
Implementation of the layout design from #142.
Currently, WizardRuleInputPanels widgets is being used here.

- [ ] Add new component implementing the new design

**Comment by ExperimentsInHonesty** [comment] 2020-02-15 19:12
Duplicate of issue Bradley is working on #232

**Closed by ExperimentsInHonesty** 2020-02-15 19:12 UTC
Labels: duplicate
