### ISSUE TITLE
Provide a form for viewing and editing a list of Calculations in the Calculation table.

### ISSUE THREAD

**Issue by entrotech** [hackforla/tdm-calculator#43] opened 2019-08-06 22:36 UTC
This is a lower-priority issue, since it's not clear that we will ever need "alternative" calculations to the TDM calculation.  This might come into play if we want to create alternative TDM calculations for other cities with a different set of rules. (Though they would probably also want the UI skinned differently as well.)

**Comment by ExperimentsInHonesty** [comment] 2019-12-22 19:43
The project would make the project useable by other cities and other calculation needs not even related to TDM

**Comment by ExperimentsInHonesty** [comment] 2019-12-22 19:46
see issue #46

**Comment by KPHowley** [comment] 2021-08-03 18:36
closing as this is a duplicate of #46

**Closed** 2021-08-03 18:36 UTC
