### ISSUE TITLE
UX review with Hack for LA members

### ISSUE THREAD

**Issue by amberyou** [hackforla/tdm-calculator#397] opened 2020-05-28 23:31 UTC
### Overview
We will test the TDM website with Hack for LA members outside of the TDM team in order to gain feedback and identify possible improvements to the user experience

### Action Items

- [x] Go meet with the Undebate team and get feedback
   - [x] Type up feedback

### Resources/Instructions
[Staging website](https://tdm-calc-staging.herokuapp.com/)

**Comment by amberyou** [comment] 2020-05-28 23:43
1. In addition to having 'arrow buttons' include text saying 'next page,' And it would be helpful to have a progress bar.
2. It is easy to miss 'verified' message when verifying my email at the sign up.
3. If the side dashboard is fixed (sticky), it would be easier to look at it as I input information.
4. Having fewer choices for the screen would make the user's experience better.
5. There should be a warning sign when I cannot save the project after entering in all the information because I have not created an account yet.
6. In the projects page, the text would look better if it is all justified the same way
7. Was not clear that checking a box would change 'earned points' and that earned should meet 'target points'

@ExperimentsInHonesty @KPHowley @dazainus

**Comment by ExperimentsInHonesty** [comment] 2020-05-29 00:39
Here some additional context for the above:

 #2 above, the message is at the bottom of the page, and David, the reviewer said that it should be centered above the login content in the body section.   See big white space in image below:
![Screen Shot 2020-05-28 at 4 51 56 PM](https://user-images.githubusercontent.com/37763229/83205531-a09f7500-a103-11ea-9518-14185bbab89d.png)

#4 There are two pages that this observation effects.  
**Status:** We have spent significant time on this issue with them already.  We have to be careful not to be seen as re-litigating things that they have already decided before we have the pressure of outside user texting with the target focus group.  But it is possible we can make a small change.
**Background:** Because of the complexity of the categories (i.e., 
**Retail Inputs** containing things like Medical Offices, Clinics, Service Facilities as opposed to **Commercial Inputs** containing things like Restaurant/Bar/General, Health Club, Take-out Restaurant, Office, Business, Manufacturing, Industrial and Warehouse) 
a determination was made to put all the sub categories under their headings on one page.  Otherwise developer users won't know which main category their items fall into.  Even LADOT staff could not always remember which subcategories were where.

**What we could potentially do is add the text "check all that apply"**
![Screen Shot 2020-05-28 at 5 00 12 PM](https://user-images.githubusercontent.com/37763229/83206051-edd01680-a104-11ea-9e84-e9e30830ab87.png)

Having said all that, we did show LADOT a mockup of this page with alternate display options.  They decided to have it display all at once.  See recommendation images: [Accordion](https://www.figma.com/file/qNgPc5lttpf0SWSwkbbWyT/TDM-Calculator?node-id=533%3A13) and [Tabs](https://www.figma.com/file/qNgPc5lttpf0SWSwkbbWyT/TDM-Calculator?node-id=523%3A2)
![Screen Shot 2020-05-28 at 5 17 15 PM](https://user-images.githubusercontent.com/37763229/83207123-47d1db80-a107-11ea-9878-c1ad62ff533c.png)

#5 The problem is really that when you first load the application that it goes straight to setting up a new project.  What if when they are not logged in, it just took them to a page that said, you are not logged in, do you want to create a project without saving, or save your work, by logging in first.  Or something like that.

#6 this is resolved in the new version of this page that @dazainus  is working on.

**Closed** 2020-06-20 16:56 UTC
Labels: good first issue, research, ui/ux
