### ISSUE TITLE
Fix Select Residential Package button

### ISSUE THREAD

**Issue by fyliu** [hackforla/tdm-calculator#271] opened 2020-03-03 19:37 UTC
### Overview
From @nclairesays on slack: It seems like the Residential Package button is gone? I see the commercial one

Problem behavior found at commit 350e14b and not before. This was where we refactored the wizard pages into separate components and pre-filtered the rules that were then passed in to each one. The ProjectMeasures page needed to look for a land use rule to display the Residential Package button, but that's been filtered out.

### Action Items
- [ ] pass in all the rules or pass in just the relevant rule as a prop

**Comment by fyliu** [comment] 2020-03-03 20:03
![Screenshot from 2020-03-03 11-39-40](https://user-images.githubusercontent.com/1160105/75814626-ee941f00-5d46-11ea-9018-4499b21644bc.png)

**Comment by entrotech** [comment] 2020-03-04 17:17
Quick fix merged directly with develop branch (by mistake, but its done)

**Closed by entrotech** 2020-03-04 17:17 UTC
Labels: bug, dev: front-end, level: easy

**Comment by KPHowley** [comment] 2020-03-06 20:43
reviewed, and the buttons now appear as intended
