### ISSUE TITLE
Implement tag system to allow for multiple AIN's to be entered on Page 1 

### ISSUE THREAD

**Issue by KPHowley** [hackforla/tdm-calculator#1010] opened 2021-12-02 02:41 UTC
### Overview

Allow multiple AIN's to be entered in the text box for AIN #, by implementing a Tag system. 

### Action Items
- [x] Integrate react-select component
  - [x] hook up data and be able to save/load from the project
  - [x] replace the default input with input-mask
  - [x] style the component like the other input fields
- [x] "Add another" placeholder text
- [x] Allow creating invalid tags in red
    - [x] Show error message for the invalid tags
- [x] rebase to the latest dev code

### Target Features
- [x] change AIN to be turn into tag when users enter AIN information 
- [x] add tag when users hit enter, tab, ","
- [x] add tag when users go past the required amount of numbers
- [x] allow for tags to be removed by clicking on "x" 
- [ ] ~allow for tags to be edited by double clicking on target tag or hitting backspace~

### Resources/Instructions

![Hi-fi prototype - edit](https://user-images.githubusercontent.com/82553907/150065998-a80dc722-8701-4cbc-9b64-6523ddd2bb94.png)

See mockup and prototype here: https://www.figma.com/file/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=4919%3A17250

**Comment by KPHowley** [comment] 2021-12-11 17:58
@cduong5  -can you post the latest prototype you shared here.

**Comment by cduong5** [comment] 2021-12-11 18:16
New prototype: https://www.figma.com/file/nD9QK56Mzq7xNSaSUoeGx0/TDM-Calculator?node-id=5132%3A18439
Video of new prototype: https://www.awesomescreenshot.com/video/6355727?key=8c276657df3b090b4d32b5310cb51049

**Comment by ExperimentsInHonesty** [comment] 2022-01-15 18:49
@fyliu Please provide update
1. Progress
2. Blockers
3. Availability
4. ETA

**Comment by fyliu** [comment] 2022-01-15 20:22
I found a package (react select) that can potentially be made to do exactly what we need. My plan is to first hook up the data to it and then tweak the styling.
No blockers
I can spend maybe 4 hours on it this week
ETA 2 weeks since I'm not sure if I can finish this week

**Comment by fyliu** [comment] 2022-01-27 03:31
1. Progress - I gained more understanding of the select component but didn't make much progress because of not being able to spend time on this.
2. Blockers - I had problem getting the styling right. Need to understand it better. Need to figure out how to hook up the component's events to what we have in onInputChange in TdmCalculationContainer.
3. Availability - I might not be able to work on this for the next week
4. ETA - Maybe in 2 weeks

**Comment by fyliu** [comment] 2022-02-02 23:39
1. Progress - I tried to make progress and discovered I need to learn something first. I ended up researching how to create custom events
2. Blockers - I need to know how to create and pass a custom event up the component tree
3. Availability - I can work on it more Thursday and maybe next week
4. ETA - depends on the blocker. Maybe in 2 weeks.

**Comment by fyliu** [comment] 2022-02-08 23:57
1. Progress - I hooked up the data part of the component. It can load and save the tags in the project as a comma separated string. Any input not turned into tags are considered lost if the user focuses away from the input field.
2. Blockers - I'm working on adding the input mask into the input component
3. Availability - a couple days this week
4. ETA - Maybe I'll have the main functionality working next week

**Comment by fyliu** [comment] 2022-02-10 04:39
Notes after reading the current Figma design. I need to evaluate the feasibility of these requirements.

1. The design wants to override the AIN box's error text with one generated by the tags inside it. So "AIN/APN field is required" could turn into "Each AIN/APN must be 10 digits".
2. The design wants to enable the red outline on the AIN box when displaying the tag error message.
3. The design wants to do tag validation and display the improper tags in red color.
4. The design wants to turn the tags into input fields when the user clicks on them. This is not feasible since the tags are displays and don't contain editing logic. The way to achieve a similar result right now is to delete the tag and re-enter it in the input field.
    1. It may be possible to click on a tag and move the contents of it into the input field.

**Comment by fyliu** [comment] 2022-02-12 05:37
1. Progress - I added some validation to the display tags and I'm working on the "Add another" placeholder text
2. Blockers
    1. I lost 2 days due to my child being sick
    2. Still need to tweak styling to match other input fields, which wasn't worked on since last time.
    3. Need to discuss some of the items above that I just found out about. Some are not easy or doesn't make sense.
3. Availability - 4 hours before the next meeting
4. ETA - 2/23

**Comment by fyliu** [comment] 2022-02-24 00:11
1. Progress - placeholder text works, input cursor jumps to the last digit
    remaining tasks:
    - [ ] style the input field
    - [ ] display error message if the tags are invalid
2. Blockers - need help on CSS spacing

<details>
    <summary>click left triangle to expand to view the problem</summary>

![2022-02-23 16 02 44 localhost 215226a98f75](https://user-images.githubusercontent.com/1160105/155431622-8f52ee3c-34d0-40b0-aa96-8b29e2e7eb27.png)

</details>

3. Availability - 1 day this week and 1 day next week
4. ETA - I'd give it a week but it could be shorter or longer

**Comment by fyliu** [comment] 2022-02-28 06:49
1. Progress - All done but I'm doing more testing
    1. Bug: AIN errors don't show up when loading project with invalid AIN 
2. Blockers - none
3. Availability - A few more hours before 3/2
4. ETA - Should be done by 3/2

@seenaiype
Some screenshots hidden below
<details>
  <summary>click to expand</summary>

![Screenshot from 2022-02-27 22-38-14](https://user-images.githubusercontent.com/1160105/155936951-8ac9c3dc-485b-413c-ad56-0e32864d9248.png)
![Screenshot from 2022-02-27 22-38-41](https://user-images.githubusercontent.com/1160105/155936955-318ddec2-a057-4f90-87d3-9ef0eb0d4257.png)

</details>

**Comment by fyliu** [comment] 2022-03-01 23:29
Question: Should an invalid AIN tag cause navigation to be disabled?

**Comment by KPHowley** [comment] 2022-03-02 21:16
@fyliu - if this is a required field (which it is) we should verify the length is correct on AIN

**Comment by fyliu** [comment] 2022-03-03 03:52
From the meeting, we (@KPHowley, @Shaeeka, @fyliu) decided that it's better to not allow users to create invalid tags that they would then have to delete and re-enter with the correct number. We want to create only valid tags. The next button logic would stay the same, it'd be enabled if there's any tags are present (with other required inputs satisfied).

Browsers render a highlight around the active input fields. It makes the AIN input halo around the mask rather than the whole AIN box. We want to have it look consistent with the other input boxes.

**Comment by ExperimentsInHonesty** [comment] 2022-03-12 19:02
@Shaeeka please make a new issue to create a work around for the highlighting of the ain cell.  We decided that it was going to be solved by the numbers appearing outside of the box, and the box only having enter a new number in it.  As soon as you press enter, it should move the numbers to a gray tag above and keep you in the box the box to enter again.

When you finish making the issue, please close this issue and add the number of the new issue here

**Comment by fyliu** [comment] 2022-03-16 05:49
My fault for tagging the pull request to close the issue. The pull request was all the functionality minus the last bit of UI tweaking for the input focus we talked about at a previous meeting.

It seems like the problem is in the Input Mask component taking that focus. The React Select component displays the input focus behavior the same way the design specified. I tried for a while and it feels like there's no way to make it work like the original design if we want to keep using Input Mask.

The workaround that Bonnie mentioned could be a viable way to do this. We just make Input Mask into the input field and let it take the input focus. We remove the original outline of the React Select component and display the AIN values if they're available. The only thing is collapsing the empty space when there's no AIN value yet.

Anyway, these are my thoughts on how to continue with this.

**Comment by fyliu** [comment] 2022-03-19 17:12
1. Progress - Separated the AIN values and the input field. Need to expand the input border to fill up the entire line
2. Blockers - None
3. Availability - 4 hrs before next team meeting
4. ETA - 3/23 next meeting

**Comment by fyliu** [comment] 2022-03-24 02:16
1. Progress - The AIN values are now above the input field. The input field highlight shows up properly.
2. Blockers - None
3. Availability - 4hrs before next meeting
4. ETA - should be done unless there are changes requested

**Comment by fyliu** [comment] 2022-03-24 03:33
At the meeting, we decided to do these updates
- [ ] more vertical spacing
- [ ] show invalid AIN input after focusing away
- [ ] auto create AIN when focusing away if input is valid

**Comment by fyliu** [comment] 2022-03-24 14:59
I did the fixes discusses yesterday but the following is not resolved and will take longer than today's merge deadline.

Question: Is it okay if the Next page button is not disabled when there's an error in the AIN input? 

Question 2: Should the AIN length error or the empty input error have priority?

**Comment by fyliu** [comment] 2022-03-31 03:13
From the meeting tonight.
1. Don't make any more changes before user testing is done
1. There's a bug that display the 10 digits error message when the input field is empty
1. Answer to question 1: We do want to have the AIN input error about 10 digits to disable the Next button
1. Answer to question 2: The way things currently are is fine. When there's no complete AIN and there's partially filled AIN input, it should show the error message about each AIN needing 10 digits
1. The solid red error border for the AIN input box is okay (I pointed out it's a different style than the other error borders)

**Comment by fyliu** [comment] 2022-03-31 17:27
Fixes:
- [x] Empty AIN input shouldn't show an error
- [x] AIN input error disables next navigation

New problem:
- backspace doesn't delete completed AIN once the input has been typed on

**Comment by fyliu** [comment] 2022-04-04 22:59
Update: the backspace doesn't delete AIN problem has to do with the React Input Mask component stopping propagation of the backspace event. I don't know if that's a thing that all inputs do, but the React Select component relies on the event to work correctly. Our choices are these:
1. Don't use the input mask. Use the input that comes with React Select that works correctly
   1. no input mask, which I don't think we want
1. Replace the input mask with something we make ourselves
   1. remaking the component takes time and probably a lot of debugging
1. Modify the input mask code and use that
   1. adding the whole code into our code base has licensing issues
   1. modifying and publishing the code under another name on npm solves the licensing issues
      1. there may be maintenance work required if the upstream gets updates
1. Continue looking for another alternative
   1. this may be stuck forever

The above are the options and the drawbacks of each. This is a big issue for keyboard-only usage. It's not a problem if the user can use a mouse pointer.

**Comment by Biuwa** [comment] 2022-04-14 02:33
Please confirm if this issue will be continuing or if a new issue replaces this @fyliu @KPHowley

**Closed** 2022-04-21 02:07 UTC
Labels: role: front-end, level: hard, priority: MUST HAVE, p-Feature - Project Page, milestone: missing
